# Book settings
title: Jupyter Guide to Linear Algebra
author: Ben Vanderlei
logo: reflection_logo.png

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/bvanderlei/jupyter-guide-to-linear-algebra
  branch: main

launch_buttons:
  notebook_interface: "classic"
  thebe: true